---
wireguard_enabled: false
wireguard_user_id: "{{ default_owner }}"
wireguard_group_id: "{{ default_group }}"

# directories
wireguard_data_directory: "{{ docker_home }}/wireguard"
wireguard_compose_file: "{{ wireguard_data_directory }}/docker-compose.yaml"
wireguard_config_file: "{{ wireguard_data_directory }}/wireguard.yaml"
# network

# docker
wireguard_container_name: "wireguard"
wireguard_network_name: docker_network
wireguard_tag_name: tag:container

# specs
wireguard_memory: "200m"
wireguard_cpu: 1
wireguard_port: 51820
wireguard_server_url: "your.server.url"
wireguard_peers: 1
wireguard_internal_subnet: "10.13.13.0"
wireguard_allowed_ips: "0.0.0.0/0"

